'use strict'
// Please don't delete the 'use strict' line above

const donutbody = [
  {
    Name: "生地を選択してください",
    Description: "",
    Calory: 0,
    Price: 0,
    AddName: "",
  },
  {
    Name: "オールドパッション",
    Description: "シンプルでオーソドックスな生地",
    Calory: 280,
    Price: 150,
    AddName: "パッション",
  },
  {
    Name: "プンデリング",
    Description: "みんな大好き、フジドの救世主",
    Calory: 200,
    Price: 160,
    AddName: "プンデリング",
  },
  {
    Name: "イタリアンクルーラー",
    Description: "フワフワ食感のバニラ味",
    Calory: 120,
    Price: 140,
    AddName: "クルーラー",
  },
];

const process1 = [
  {
    Name: "サンドしない",
    Description: "",
    Calory: 0,
    Price: 0,
    AddName: "",
  },
  { Name: "エンゼル", 
    Description: "ホイップクリームをサンドする",
    Calory: 20,
    Price: 10,
    AddName: "エンゼル",
   },
  { Name: "カスタード",
    Description: "カスタードクリームをサンドする",
    Calory: 40,
    Price: 15,
    AddName: "カスタード",
   },
];
const process2 = [
  {
    Name: "ディップしない",
    Description: "",
    Calory: 0,
    Price: 0,
    AddName: "",
  },
  { Name: "グレーズ",
    Description: "グレーズ（砂糖を溶かした液体）にディップする" ,
    Calory: 30,
    Price: 10,
    AddName: "ハニー",
    },
  { Name: "チョコ",
    Description: "チョコレートにディップする",
    Calory: 35,
    Price: 10,
    AddName: "チョコ",
    },
  { Name: "ストロベリー",
    Description: "ストロベリーチョコにディップする",
    Calory: 40,
    Price: 10,
    AddName: "ストロベリー",
    },
  { Name: "ホワイト",
    Description: "ホワイトチョコにディップする",
    Calory: 50,
    Price: 10,
    AddName: "ホワイト",
    },  
];
const process3 = [
  {
    Name: "トッピングしない",
    Description: "",
    Calory: 0,
    Price: 0,
    AddName: "",
  },
  { Name: "シュガー",
    Description: "シュガーをまぶす",
    Calory: 5,
    Price: 5,
    AddName: "シュガー",
    },
    { Name: "シナモン",
    Description: "シナモンをまぶす",
    Calory: 10,
    Price: 5,
    AddName: "シナモン",
    },
  { Name: "チョコ掛け",
    Description: "チョコを線掛けする",
    Calory: 10,
    Price: 10,
    AddName: "",
    },
  { Name: "ゴールデン",
    Description: "ゴールデントッピングをつける",
    Calory: 20,
    Price: 10,
    AddName: "ゴールデン",
    },
];
