'use strict'
// Please don't delete the 'use strict' line above

const donutbody = [
  {
    Name: "オールドパッション",
    Description: "シンプルでオーソドックスな生地",
    Calory: 220,
    Price: 30,
    AddName: "パッション",
  },
  {
    Name: "プンデリング",
    Description: "みんな大好き、フジドの救世主",
    Calory: 220,
    Price: 30,
    AddName: "プンデリング",
  },
];

const process1 = [
  { Name: "エンゼル", 
    Description: "ホイップクリームをサンドする",
    Calory: 50,
    Price: 10,
    AddName: "エンゼル",
   },
  { Name: "カスタード",
    Description: "カスタードクリームをサンドする",
    Calory: 50,
    Price: 10,
    AddName: "カスタード",
   },
];
const process2 = [
  { Name: "グレーズ",
    Description: "グレーズ（砂糖を溶かした液体）にディップする" ,
    Calory: 50,
    Price: 10,
    AddName: "ハニー",
    },
  { Name: "チョコ",
    Description: "チョコレートにディップする",
    Calory: 50,
    Price: 10,
    AddName: "チョコ",
    },
  { Name: "ストロベリー",
    Description: "ストロベリーチョコにディップする",
    Calory: 50,
    Price: 10,
    AddName: "ストロベリー",
    },
  { Name: "ホワイト",
    Description: "ホワイトチョコにディップする",
    Calory: 50,
    Price: 10,
    AddName: "ホワイト",
    },  
];
const process3 = [
  { Name: "シュガー",
    Description: "シュガーをまぶす",
    Calory: 50,
    Price: 10,
    AddName: "シュガー",
    },
  { Name: "チョコ掛け",
    Description: "チョコを線掛けする",
    Calory: 50,
    Price: 10,
    AddName: "",
    },
  { Name: "ゴールデン",
    Description: "ゴールデントッピングをつける",
    Calory: 50,
    Price: 10,
    AddName: "ゴールデン",
    },
];
